version: "3"
services:
  bitcoind:
    image: btcpayserver/bitcoin:0.17.0
    environment:
      BITCOIN_NETWORK: testnet
      BITCOIN_EXTRA_ARGS: |
        testnet=1
        whitelist=0.0.0.0/0
        rpcport=43782
        port=39388
        server=1
        rpcuser=yolo
        rpcpassword=yolo
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
        deprecatedrpc=signrawtransaction
    expose:
      - "43782" # RPC
      - "39388" # P2P
      - "28332" # ZMQ
      - "28333" # ZMQ
    ports:
      - "43782:43782"
    volumes:
      - "./data/bitcoin:/data"
  lnd-testnet:
    image: btcpayserver/lnd:v0.5.1-beta
    environment: # tlsextraip allows you to add outside ip to give access to gprc
      LND_EXTRA_ARGS: |
        [Application Options]
        externalip=*.*.*.*:9735
        debuglevel=debug
        maxpendingchannels=500
        rpclisten=0.0.0.0:10009
        restlisten=0.0.0.0:8080
        tlsextraip=192.168.1.89
        tlsextraip=172.30.255.255
        tlsextraip=0.0.0.0
        [bitcoin]
        bitcoin.active=1
        bitcoin.testnet=1
        bitcoin.node=bitcoind
        [bitcoind]
        bitcoind.dir=/bitcoin
        bitcoind.rpcuser=yolo
        bitcoind.rpcpass=yolo
        bitcoind.rpchost=bitcoind:43782
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        [autopilot]
        autopilot.active=1
        autopilot.maxchannels=500
        autopilot.minconfs=1
        autopilot.allocation=0.9
    ports:
      - 8081:8080
      - 10009:10009
      - 9735:9735
    volumes:
      - ./data/lnd:/data
      - ./data/bitcoin:/bitcoin
    links:
      - bitcoind
