version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - 6381:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data
    volumes:
      - .docker/data/postgresql:/data
  redis:
    image: redis:4.0.10
    ports:
      - 6382:6379
    volumes:
      - .docker/data/redis:/data