#!/usr/bin/env bash

git subtree split --prefix drink_db -b deploy
git checkout deploy
cp drink_db/.env .
python3 bridge/login.py
git add --force *.pickle
git add --force *get.html
git add --force *post.html
git status
git commit -m "Added credentials"
git checkout master --force
git push heroku deploy:master --force
git branch -D deploy
heroku run rake db:migrate db:seed
